version: 2

sources:
  - name: staging
    database: yt_subs
    schema: landing_area
    tables:
      - name: yt_video_sub_timecodes

models:
  - name: stg_yt_subs
    description: "A starter dbt model"
    columns:
      - name: text
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: start
        data_tests:
          - unique
          - not_null
      - name: duration
        data_tests:
            - unique
            - not_null
      - name: youtube_id
        data_tests:
            - unique
            - not_null